### ISSUE TITLE
bug: progressbar not cleared after span closed

### ISSUE THREAD

**Issue by mokurin000** [emersonford/tracing-indicatif#10]
```rust
#![feature(mpmc_channel)]

use std::{error::Error, time::Duration};

use indicatif::ProgressStyle;
use rand::random;
use tracing::{info_span, Level};
use tracing_core::LevelFilter;
use tracing_indicatif::{span_ext::IndicatifSpanExt, IndicatifLayer};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, Layer};

type Result<T> = std::result::Result<T, Box<dyn Error + Sync + Send>>;

const WORKER_NUM: Option<&str> = option_env!("WORKER_NUM");

#[tokio::main]
async fn main() -> Result<()> {
    let indicatif_layer = IndicatifLayer::new()
        .with_progress_style(
            ProgressStyle::default_bar()
                .template(
                    "{spinner:.green} {msg} [{bar:40.cyan/blue}] {bytes}/{total_bytes} ({eta})",
                )?
                .progress_chars("#>-"),
        )
        .with_max_progress_bars(u64::MAX, None);
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::fmt::layer()
                .with_level(true)
                .with_writer(indicatif_layer.get_stderr_writer())
                .with_filter(LevelFilter::from_level(Level::DEBUG)),
        )
        .with(indicatif_layer)
        .init();

    let (tx, rx) = std::sync::mpmc::channel();

    for _ in 0..WORKER_NUM.unwrap_or("4").parse()? {
        let rx = rx.clone();
        tokio::spawn(async move {
            while let Ok(_) = rx.recv() {
                payload().await
            }
        });
    }
    drop(rx);

    loop {
        let _ = tx.send(());
    }
}

async fn payload() {
    let target: u32 = random::<u16>() as u32 * 1000;

    let span = info_span!("download");
    span.pb_set_length(target as _);
    let _enter = span.enter();

    let mut cur: u32 = 0;
    let speed = 1024 * 1024;
    loop {
        cur += speed;

        span.pb_set_position(cur.min(target) as _);
        if cur >= target {
            drop(_enter);
            drop(span);
            break;
        }

        tokio::time::sleep(Duration::from_millis(50)).await;
    }
}
```
![image](https://github.com/user-attachments/assets/68d81967-c911-41a4-bbe7-5ed6ce71eb56)

**Comment by emersonford** [comment]
Is it a deadlock in that the program never terminates? Or just that the progress bar doesn't disappear, but the program still exits?

**Comment by mokurin000** [comment]
> Is it a deadlock in that the program never terminates? Or just that the progress bar doesn't disappear, but the program still exits?

Nope. It's the progress bar never disappear.
on_close triggered, but the pb_manager lock cannot be acquired

**Comment by mokurin000** [comment]
> Is it a deadlock in that the program never terminates? Or just that the progress bar doesn't disappear, but the program still exits?

I will write a minimum reproduce code later. Also, in the multithread example, everything works fine; the main difference to the example is, tasks were spawned on tokio multithread runtime.

**Comment by mokurin000** [comment]
@emersonford could you check my example code?

https://github.com/kawaii-hentai-dev/tracing-indicatif/blob/fix-deadlock/examples/tokio-multithread.rs

**Comment by mokurin000** [comment]
@emersonford any idea?

**Comment by ysndr** [comment]
We have the same issue when using `Span::in_scope`, where apparently explicitly `drop`ping helps:

```rust
let span = info_span!("install", ...);
let installation = span.in_scope(|| environment.install(&packages_to_install, &flox));

// uncomment to clear progress bar
// drop(span);
```

**Comment by mokurin000** [comment]
> We have the same issue when using `Span::in_scope`, where apparently explicitly `drop`ping helps:
> 
> ```rust
> let span = info_span!("install", ...);
> let installation = span.in_scope(|| environment.install(&packages_to_install, &flox));
> 
> // uncomment to clear progress bar
> // drop(span);
> ```

Because the use of async in closures is not yet stablized, I cannot switch to in_scope. But I also dropped guard and span manually

**Comment by mokurin000** [comment]
> We have the same issue when using `Span::in_scope`, where apparently explicitly `drop`ping helps:
> 
> ```rust
> let span = info_span!("install", ...);
> let installation = span.in_scope(|| environment.install(&packages_to_install, &flox));
> 
> // uncomment to clear progress bar
> // drop(span);
> ```

Could you please tell me, is your code single-threaded? I've noticed, with WORKER_NUM set to 1, my example code works fine

**Comment by ysndr** [comment]
There is a multithreaded tokio runtime around this yes. Up to this point though it doesn't run concurrently with any other task tho.

**Comment by ysndr** [comment]
@mokurin000 oybthing I can see in your code (from quickly glancing at it now) is that you are holding a the span created in line 59 across an await point which is not advisable: https://docs.rs/tracing/latest/tracing/span/struct.Span.html#in-asynchronous-code

I believe that might correspond to parts of the data being thread local but your entered span switching threads due to await.

Did you give it a try using the instrument annotation or Future method instead? That should have the proper precautions in place to deal with async functions.

**Comment by mokurin000** [comment]
> @mokurin000 one thing I can see in your code (from quickly glancing at it now) is that you are holding a the span created in line 59 across an await point which is not advisable: https://docs.rs/tracing/latest/tracing/span/struct.Span.html#in-asynchronous-code
> 
> I believe that might correspond to parts of the data being thread local but your entered span switching threads due to await.
> 
> Did you give it a try using the instrument annotation or Future method instead? That should have the proper precautions in place to deal with async functions.

Thanks, adding #[tracing::instrument] solved the issue

I will checkout an example branch later
