### ISSUE TITLE
max_progress_bars deadlocks

### ISSUE THREAD

**Issue by Kyuuhachi** [emersonford/tracing-indicatif#2]
Entering a large number of spans simultaneously on different threads seem to cause deadlocks. Raising `with_max_progress_bars` avoids this, which hints that the limiting is what causes the deadlock.

I encountered this issue ussing Rayon (which on my machine uses 8 threads by default, which is slightly above the default limit of 7 bars), but the example below is written with plain threads.

```rs
use tracing_indicatif::IndicatifLayer;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;

fn main() {
	let indicatif_layer = IndicatifLayer::new();
	tracing_subscriber::registry()
		.with(tracing_subscriber::fmt::layer().with_writer(indicatif_layer.get_stderr_writer()))
		.with(indicatif_layer)
		.init();

	let handles = (0..256).map(|i| {
		std::thread::spawn(move || {
			tracing::info!("before {i}");
			let _span = tracing::info_span!("ch").entered();
			tracing::info!("after {i}");
		})
	}).collect::<Vec<_>>();
	handles.into_iter().for_each(|i| i.join().unwrap());
}
```

**Comment by emersonford** [comment]
thanks for the reporting and the simple repro! make it super easy to track down the culprit.

I discovered that `.extensions()` and `.extensions_mut()` take a lock (which isn't documented anywhere?) and that spooked me a bit... looks like for good reason too! will release 0.3.2 shortly with the fix.
