### ISSUE TITLE
Another race condition, causing poison

### ISSUE THREAD

**Issue by Kyuuhachi** [emersonford/tracing-indicatif#3]
This one seems a little more subtle than #2, but under certain conditions it seem a race condition causes `None.unwrap()`:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-indicatif-0.3.2/src/pb_manager.rs:140:69
```

Followed by any subsequent use getting a poison error:
```
thread '<unnamed>' panicked at 'Mutex poisoned: PoisonError { .. }', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.17/src/registry/sharded.rs:433:54
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-indicatif-0.3.2/src/lib.rs:546:22
```

The repro is almost the same as in #2, but with the `info!` statements removed. Presumably they either cause synchronization via `get_stderr_writer`, or simply affect the timing. It's not guaranteed to happen; for me it happens about every other time when running this program in debug build.

``` rs
use tracing_indicatif::IndicatifLayer;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;

fn main() {
	let indicatif_layer = IndicatifLayer::new();
	tracing_subscriber::registry()
		.with(tracing_subscriber::fmt::layer().with_writer(indicatif_layer.get_stderr_writer()))
		.with(indicatif_layer)
		.init();

	let handles = (0..256)
		.map(|_| {
			std::thread::spawn(move || {
				let _span = tracing::info_span!("ch").entered();
			})
		})
		.collect::<Vec<_>>();
	handles.into_iter().for_each(|i| i.join().unwrap());
}
```

**Comment by emersonford** [comment]
Oh wow, that is super subtle. Looks like what happened is I assume the span is removed from the tracing registry as soon as `on_close` is finished... but it's possible there are other layers (ergo other `on_close` calls) tracing has to iterate through first before it can remove the span from the registry. So there's a brief period where we have closed out the progress bar (from `IndicatifLayer`'s `on_close` call) but the span still exists in the registry, and I incorrectly assume that "if span exists in registry, it must still have a progress bar."

the fix here is to check whether we have a progress bar when we grab a span off the tracing registry. I've run this repro a few thousands times now with the fix and have not encountered a panic, so feel very confident I have fixed this race condition as well.

Thanks again for finding and reporting this! Will put out another release shortly with this fix. :)
