### ISSUE TITLE
Suspend output for some time to interact with the console

### ISSUE THREAD

**Issue by DCNick3** [emersonford/tracing-indicatif#4]
While it is possible to use the stdout/stderr wrappers to output something to the console, for some use-cases this is not enough.

I want to prompt the user with a selection using [dialoguer](https://github.com/console-rs/dialoguer), which wants to have the _real_ terminal writer (by having an `AsRawFd` trait bound on the `Term` constructor).

I _think_ this can be ultimately accomplished by exposing the `suspend` function of the `MultiProgress`, allowing to hide progress bars during the user interaction (as suggested in https://github.com/console-rs/indicatif/issues/158). This has a side-effect of blocking every other thing that tries to write to the output (including the tracing fmt layer if it was registered), but I think there's no real way to multiplex that..

**Comment by emersonford** [comment]
closed with v0.3.5, apologies it took a while for me to get around to this :)
