### ISSUE TITLE
This project is really nice

### ISSUE THREAD

**Issue by konstin** [emersonford/tracing-indicatif#5]
I've added tracing-indicatif to an internal tool recently and it's so simple and so useful

[Peek 2023-08-31 20-15 3.webm](https://github.com/emersonford/tracing-indicatif/assets/6826232/7d5c3e67-18f0-4db9-8460-1469d5759f09)

I don't even need to write custom slow file tracking tooling anymore, i can just watch and see which entries are slow, i get to see the configuration live and even logging while using a progress bar just works!

**Comment by emersonford** [comment]
Happy to hear it's useful, thanks for the feedback! :)
