### ISSUE TITLE
Feature Request: Configurable tick interval

### ISSUE THREAD

**Issue by junderw** [emersonford/tracing-indicatif#6]
There are two places where `enable_steady_tick` is called with a hard coded 100ms value.

Personal preference: I like 1 second re-draws for these types of things...

It would be nice to have a way to configure it:

1. Change the value, with default 100ms if not changed.
2. Ability to disable the tick (ie. it only draws when we call another method that draws like set position, inc, etc.)

I would like to add: this library is really great!

**Comment by emersonford** [comment]
Know this was requested over a year ago, but better late than never I suppose. :D 

This functionality is available as of v0.3.8.
