### ISSUE TITLE
How to log progress bar to file

### ISSUE THREAD

**Issue by Halimao** [emersonford/tracing-indicatif#7]
Hi, nice work! This crate saved my day😀. 
Could I use this crate to record progress bar in log file? I didn't find any way to make it neither through the documents, nor from the source code. Could u please give me some advice? Thanks 🙏🏻

**Comment by Halimao** [comment]
@emersonford Hi sir, could you please help me figure this out😀

**Comment by emersonford** [comment]
Can you give me an example of what a progress bar in a file would even look like?

**Comment by Halimao** [comment]
> Can you give me an example of what a progress bar in a file would even look like?

Refer to [FuelLabs/fuelup/pull/525 comment](https://github.com/FuelLabs/fuelup/pull/525#issuecomment-1836528318).

Maybe something like writting the final progress bar status to log file, whether it is success or failure.

Case success:
![image](https://github.com/emersonford/tracing-indicatif/assets/25278203/510d30b1-9d30-4634-8524-97b5b7e6200f)

Case failure:
TBA

**Comment by emersonford** [comment]
I'm not sure this is possible with `indicatif`. See https://docs.rs/indicatif/latest/indicatif/struct.ProgressDrawTarget.html for what indicatif supports as output targets.

**Comment by Halimao** [comment]
> I'm not sure this is possible with `indicatif`. See https://docs.rs/indicatif/latest/indicatif/struct.ProgressDrawTarget.html for what indicatif supports as output targets.

It seems that there is no implemented ProgressDrawTarget for file, I will try to find a way, thanks again, have a good day😀
