### ISSUE TITLE
Progress bars don't seem to finish?

### ISSUE THREAD

**Issue by flokli** [emersonford/tracing-indicatif#9]
I'm using `tracing-indicatif` in a stream, using the `.instrument()` function available on futures.

Something like the following:

```rust
            let num_elems = elems.len();
            let results: Vec<_> = futures::stream::iter(elems)
                .map(|elem| {
                    let some_service = some_service.clone();
                    async move {
                        let resp = some_service
                            .get(elem)
                            .await
                            .map(|resp| (elem, resp));

                        // once the .get is done, increment the progress bar.
                        Span::current().pb_inc(1);

                        resp
                    }
                })
                .buffer_unordered(10)
                .try_collect()
                .instrument({
                    let span = tracing::info_span!("doing_work", "indicatif.pb_show" = tracing::field::Empty);
                    span.pb_set_message("Doing work");
                    span.pb_set_length(num_elems);
                    span.pb_set_style(
                        &ProgressStyle::with_template(
                            "{prefix}{wide_msg} {bar:30} [{elapsed_precise}]  {pos:>7}/{len:7}",
                        )
                        .unwrap(),
                    );
                    span.pb_start();
                    span
                })
                .await?;

            do_other_work();
```

While I get progress bars, and the progress bar updates, it seems the "Doing work" progress never finishes, even after it's dropped (during `do_other_work()`).

The timer keeps counting up.

A more complete example (and screencast): https://asciinema.org/a/ap9qC60A5IjvI12vQ2IBwEHOM.

As can be seen, the "Checking paths" progress bar keeps running, even though we're already at "Ingesting paths".

**Comment by flokli** [comment]
I think this was a mistake on my side, and the span was still active.

**Comment by fgvieira** [comment]
@flokli just an unrelated question, but how did you set the `{prefix}` on the span?

**Comment by flokli** [comment]
Not sure I understand the question - we use these `ProgressStyle`s:

https://git.snix.dev/snix/snix/src/commit/927ca73ea9ac19e6fbe2c29b5994be04dc71f162/snix/tracing/src/lib.rs#L28-L45

.. and set up the subscriber somewhere further down in that file.

Actual code then just sets the `indicatif.pb_show` field in its spans.

**Comment by fgvieira** [comment]
I meant that in the progress bar style, you have a `{prefix}` placeholder:
```
&ProgressStyle::with_template(
                            "{prefix}{wide_msg} {bar:30} [{elapsed_precise}]  {pos:>7}/{len:7}",
                        )
```
but how do you set it if there is no `span.pb_set_prefix`?

**Comment by flokli** [comment]
Ah. Maybe I just copied this over from the examples / other progress bar styles. I don't know anymore.
